#!/usr/bin/env python3
"""Extract exact legacy exceptions; original sheets remain test-only oracles."""
from pathlib import Path
import ctypes, json, re, subprocess, tempfile
from PIL import Image
ROOT=Path(__file__).resolve().parents[1]
NAMES=['latin_ext','greek_cyrillic','japanese','cjk','hangul']
def shared():
    tmp=tempfile.TemporaryDirectory(); p=Path(tmp.name)
    (p/'base.c').write_text('void *font_base_addr; void *reader_font_base_addr;')
    subprocess.run(['gcc','-shared','-fPIC','-O2','-Wno-discarded-qualifiers','-I'+str(ROOT/'references/gbawriter/src'),'-I'+str(ROOT/'references/gbawriter/src/fonts'),str(ROOT/'src/entry_font.c'),str(p/'base.c'),'-o',str(p/'font.so')],check=True)
    lib=ctypes.CDLL(str(p/'font.so')); buffers=[]
    for symbol,file in [('font_base_addr','fonts.pack'),('reader_font_base_addr','reader-symbols.pack')]:
        b=ctypes.create_string_buffer((ROOT/'references/gbawriter/res'/file).read_bytes());buffers.append(b);ctypes.c_void_p.in_dll(lib,symbol).value=ctypes.addressof(b)
    lib._keep=(tmp,buffers)
    return lib

def legacy(bank):
    name='vocab_superfw_'+NAMES[bank]+'_font'
    header=(ROOT/'include'/f'{name}_sprite_font.h').read_text()
    chars=[json.loads(s) for s in re.findall(r'"(?:[^"\\]|\\.)*"',re.search(r'utf8_characters\[\].*?\{(.*?)\};',header,re.S)[1])]
    widths=list(map(int,re.findall(r'-?\d+',re.search(r'character_widths\[\].*?\{(.*?)\};',header,re.S)[1])))
    path=ROOT/'tests/fixtures/legacy-fonts'/f'{name}.bmp'
    if not path.exists():path=ROOT/'graphics'/f'{name}.bmp'
    im=Image.open(path); assert im.mode=='P' and set(im.tobytes()) <= {0,1}
    assert im.getpalette()[:6]==[255,255,255,0,0,0], 'legacy palette changed'
    cps=list(range(33,127))+list(map(ord,chars))
    for row,cp in enumerate(cps):
        cols=[sum((im.getpixel((x,row*16+y))!=0)<<y for y in range(16)) for x in range(im.width)]
        cols += [0]*(16-len(cols))
        yield cp,widths[row+1],cols

def main():
    lib=shared();out=[]; counts={}
    for bank in range(5):
        count=0
        for cp,w,cols in legacy(bank):
            if bank and cp<127:continue
            if bank==4 and cp>=0xac00:continue
            got=(ctypes.c_uint16*16)();adv=lib.entry_font_columns(cp,got)
            cell=8 if bank<2 else 16
            expected_adv=min(adv,cell)
            if cp<127 or list(got)!=cols or expected_adv!=w:
                out.append((bank,cp,w,cols));count+=1
        counts[NAMES[bank]]=count
    text='// Generated by tools/build_compact_flashcard_fonts.py; exact legacy exceptions.\n'
    text+='struct FlashcardOverride { unsigned code; unsigned char bank, advance; uint16_t columns[16]; };\n'
    text+='static const FlashcardOverride flashcard_overrides[] = {\n'
    for bank,cp,w,cols in out:text+='{'+f'{cp},{bank},{w},'+'{'+','.join(map(str,cols))+'}},\n'
    text+='};\n'
    (ROOT/'include/flashcard_overrides.h').write_text(text)
    print(json.dumps({'override_counts':counts,'records':len(out)},indent=2))
if __name__=='__main__':main()
